import Head from "next/head";
import Image from "next/image";
import Cards from "../components/Cards";
import Slide from "../components/Slide";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pizza Order App</title>
        <link
          href="https://fonts.googleapis.com/css2?family=Bitter:wght@100;200;300;400;500;600&display=swap"
          rel="stylesheet"
        />

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slide />
      <Cards />
    </div>
  );
}
